# Generated by Django 3.2.3 on 2021-05-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pd_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='device',
            name='port',
        ),
    ]
