# Generated by Django 3.2.3 on 2021-06-21 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pd_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDmon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('sleeptime', models.FloatField(default=5)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('port', models.CharField(blank=True, max_length=4)),
                ('value', models.FloatField(blank=True, default=True)),
                ('pdmon_added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdmons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
