# Generated by Django 3.2.3 on 2021-05-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pd_monitor', '0003_auto_20210529_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='ip_address',
            new_name='ip',
        ),
    ]
