# Generated by Django 3.2.3 on 2021-05-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd_monitor', '0004_rename_ip_address_device_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='value',
            field=models.FloatField(blank=True, default=True),
        ),
    ]
