# Generated by Django 3.2.3 on 2021-10-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokugo', '0002_alter_mokugo_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mokugo',
            name='ip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mokugo',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
