# Generated by Django 3.2.3 on 2021-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokugo', '0003_auto_20211003_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mokugo',
            name='ip',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mokugo',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
