# Generated by Django 3.2.3 on 2021-06-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDmon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('sleeptime', models.FloatField(default=5)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('port', models.CharField(blank=True, max_length=4)),
                ('value', models.FloatField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tctrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('sleeptime', models.FloatField(default=5)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('port', models.CharField(default=80, max_length=4)),
                ('setpoint', models.IntegerField(blank=True, default=25)),
                ('value', models.FloatField(blank=True, default=0)),
                ('output', models.FloatField(blank=True, default=0)),
                ('error', models.FloatField(blank=True, default=0)),
                ('gain', models.FloatField(blank=True, default=1)),
                ('tauI', models.FloatField(blank=True, default=100)),
                ('tauD', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
