# Generated by Django 3.2.3 on 2021-06-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tctrl',
            name='error',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tctrl',
            name='gain',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='tctrl',
            name='output',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tctrl',
            name='setpoint',
            field=models.IntegerField(blank=True, default=25),
        ),
        migrations.AlterField(
            model_name='tctrl',
            name='value',
            field=models.FloatField(blank=True),
        ),
    ]
