# Generated by Django 3.2.3 on 2021-07-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210701_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='tctrl',
            name='value_string',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
