# Generated by Django 3.2.3 on 2021-06-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tctrl',
            name='tcrtl_added_by',
        ),
        migrations.AlterField(
            model_name='tctrl',
            name='error',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tctrl',
            name='output',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tctrl',
            name='value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
