# Generated by Django 3.2.3 on 2021-07-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tctrl_value_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdmon',
            old_name='value_string',
            new_name='data_string',
        ),
    ]
