# Generated by Django 3.2.3 on 2021-06-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210624_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
