# Generated by Django 3.2.3 on 2021-07-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_value_string_pdmon_data_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tctrl',
            old_name='value_string',
            new_name='data_string',
        ),
        migrations.AlterField(
            model_name='tctrl',
            name='port',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
