# Generated by Django 3.2.3 on 2021-07-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210702_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdmon',
            name='channels',
            field=models.CharField(default='[0,1,2,3,4,5,6,7,8,9,10,11]', max_length=27),
        ),
    ]
