# Generated by Django 3.2.3 on 2021-06-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdmon',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
