# Generated by Django 3.2.3 on 2021-07-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pdmon_channels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdmon',
            old_name='channels',
            new_name='channel_string',
        ),
    ]
