# Generated by Django 3.2.3 on 2021-07-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_pdmon_data_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tctrl',
            name='data_string',
        ),
        migrations.AlterField(
            model_name='pdmon',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tctrl',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
