# Generated by Django 3.2.3 on 2021-08-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210717_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tctrl',
            old_name='tauD',
            new_name='D',
        ),
        migrations.RenameField(
            model_name='tctrl',
            old_name='tauI',
            new_name='I',
        ),
        migrations.RenameField(
            model_name='tctrl',
            old_name='gain',
            new_name='P',
        ),
    ]
