# Generated by Django 3.2.3 on 2021-08-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210804_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdmon',
            name='channel_string',
        ),
        migrations.RemoveField(
            model_name='pdmon',
            name='port',
        ),
        migrations.RemoveField(
            model_name='tctrl',
            name='error',
        ),
        migrations.RemoveField(
            model_name='tctrl',
            name='output',
        ),
        migrations.RemoveField(
            model_name='tctrl',
            name='port',
        ),
        migrations.RemoveField(
            model_name='tctrl',
            name='value',
        ),
        migrations.AddField(
            model_name='pdmon',
            name='channels',
            field=models.CharField(default='012345', max_length=6),
        ),
        migrations.AddField(
            model_name='pdmon',
            name='dVmax',
            field=models.FloatField(blank=True, default=0.5),
        ),
        migrations.AddField(
            model_name='tctrl',
            name='dTmax',
            field=models.FloatField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='pdmon',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
