# Generated by Django 3.2.3 on 2021-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210806_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdmon',
            name='channels',
            field=models.CharField(default='111111', max_length=6),
        ),
    ]
