# Generated by Django 3.2.3 on 2021-08-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_pdmon_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdmon',
            name='channels',
            field=models.CharField(default='012345', max_length=6),
        ),
    ]
