# Generated by Django 3.2.3 on 2021-09-03 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_pdmon_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tctrl',
            name='setpointmax',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tctrl',
            name='setpoint',
            field=models.IntegerField(blank=True, default=20, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
