# Generated by Django 3.2.3 on 2021-09-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210903_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdmon',
            name='sleeptime',
        ),
        migrations.RemoveField(
            model_name='tctrl',
            name='sleeptime',
        ),
    ]
