# Generated by Django 3.2.3 on 2021-09-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_pdmon_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='MokuGo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('session', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
