# Generated by Django 3.2.3 on 2021-09-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_mokugo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mokugo',
            name='session',
            field=models.BooleanField(default='False', editable=False),
        ),
    ]
