# Generated by Django 3.2.3 on 2021-10-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
