# Generated by Django 3.2.3 on 2021-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_device_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
